import React from 'react';
import airDatepicker from 'air-datepicker';
import 'air-datepicker/dist/css/datepicker.css';

import 'jquery-migrate';
import './vendor/popper.js/popper.min.js';
import './vendor/bootstrap/bootstrap.min.js';
import './vendor/master-slider/source/assets/js/masterslider.min.js';
import './vendor/cubeportfolio-full/cubeportfolio/js/jquery.cubeportfolio.min.js';
import './vendor/slick-carousel/slick/slick.js';
import './js/hs.core.js';
import './js/components/hs.header.js';
import './js/helpers/hs.hamburgers.js';
import './js/components/hs.scroll-nav.js';
import './js/components/hs.tabs.js';
import './js/components/hs.carousel.js';
import './js/components/hs.cubeportfolio.js';
import './js/components/gmap/hs.map.js';
import './js/components/hs.go-to.js';
import './js/custom.js';

import '//fonts.googleapis.com/css?family=Open+Sans:400,300,500,600,700,800|Montserrat:300,400,500,600,700,900';
import './vendor/bootstrap/bootstrap.min.css';
import './vendor/icon-awesome/css/font-awesome.min.css';
import './vendor/icon-line/css/simple-line-icons.css';
import './vendor/icon-hs/style.css';
import './vendor/icon-line-pro/style.css';
import './vendor/hamburgers/hamburgers.min.css';
import './vendor/animate.scss';
import './vendor/master-slider/source/assets/css/masterslider.main.css';
import './vendor/cubeportfolio-full/cubeportfolio/css/cubeportfolio.min.css';
import './vendor/slick-carousel/slick/slick.css';
import './css/styles.op-restaurant.css';
import './css/custom.css';
